version: "3.7"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./conf:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log